jQuery(document).ready(function($){$('.CheckCap').on('click',function(){var seen=$(this).attr("data-seen");markEpisode(seen);});function markEpiRequest(seen){$.ajax({url:'/api/animes/markEpisode',method:'post',data:{'seen':seen,'anime_id':anime_id,'number':episode_number},success:function(data){if(data.success){if(seen==1){seen=0;var content='<i class="Svg-ic"><svg><use xlink:href="#Ic-eye-slash"/></svg></i> Marcar como no visto';}else{seen=1;var content='<i class="Svg-ic"><svg><use xlink:href="#Ic-eye"/></svg></i> Marcar como visto';}
$(".CheckCap").attr("data-seen",seen).html(content);}else{alertify.error(data.error);}},error:function(){alertify.error("Ha ocurrido un error");}});}
function markEpisode(seen){if(!is_user){alertify.error("Necesitas ser usuario registrado para poder usar está opción.");return;}
if(seen==1&&!in_library){if(episode_number==1){alertify.confirm("Se agregara a la lista de los animes que estás viendo.",function(){markEpiRequest(seen)});}else{alertify.confirm("Se agregara a la lista de los animes que estás viendo, y se marcaran todos los episodios anteriores como vistos.",function(){markEpiRequest(seen)});}}else if(seen==1&&(episode_number-1)>latest_seen){alertify.confirm("Se marcaran todos los episodios anteriores como vistos, ¿estás seguro?",function(){markEpiRequest(seen)});}else if(seen==0&&latest_seen>episode_number){alertify.confirm("Se marcaran todos los episodios siguientes que has marcado visto como no vistos, ¿estás seguro?",function(){markEpiRequest(seen)});}else{markEpiRequest(seen);}}
$('.AADrpd').each(function(){var $AADrpdwn=$(this);$('.AALink',$AADrpdwn).click(function(e){e.preventDefault();$AADrpdDv=$('.AACont',$AADrpdwn);$AADrpdDv.parent('.AADrpd').toggleClass('open');$('.AACont').not($AADrpdDv).parent('.AADrpd').removeClass('open');return false;});});$(document).on('click',function(e){if($(e.target).closest('.AACont').length===0){$('.AACont').parent('.AADrpd').removeClass('open');}});$('.AATggl').on('click',function(){var shwhdd=$(this).attr('data-tggl');$('#'+shwhdd).toggleClass('open');});$('.AACrdn').find('.AALink').click(function(){$(this).toggleClass('on');$('.AALink').not($(this)).removeClass('on');});$('.AASbmn>a').click(function(a){a.preventDefault();var b=$(this);if(b.parent().hasClass('open')){b.parent().removeClass('open');}
else{b.parent().parent().find('.AASbmn').removeClass('open');b.parent().toggleClass('open');}});$('.Slider .owl-carousel').owlCarousel({items:1,autoHeight:true,loop:true});$('.Carousel .owl-carousel').owlCarousel({autoHeight:true,loop:true,responsive:{0:{items:3,dots:true},480:{items:4,dots:true},768:{items:5,dots:true},992:{items:6,dots:true}}});var lang;initEpisode=function(){var x,langs={'ENG':'Japonese','LAT':'Sub Español','CASTE':'Castellano'};lang=("SUB"in videos)?'SUB':Object.keys(videos)[0];if(Object.keys(videos).length>1){var lbox='<div class="mm-dropdown"><div class="textfirst"><img src="images/20220117_141527.png"'+lang+'.png" alt="'+lang+'"> '+langs[lang]+'</div><ul>';for(x in videos)
lbox+='<li class="input-option" data-value="'+x+'"><img src="images/20220117_141527.png" alt="'+x+'"> '+langs[x]+'</li>';lbox+='</ul><input type="hidden" class="option" name="namesubmit" value="" /></div>';$(".lang-op").append(lbox);}
cvids(lang);}
cvids=function(lg){$(".TbVideoNv").empty();for(x in videos[lg])
$(".TbVideoNv").append('<li role="presentation" data-id="'+x+'"><a href="#option'+x+'">'+videos[lg][x]['title']+'</a></li>');setTimeout(function(){$(".TbVideoNv li:first").trigger("click");},50);};$(document).on("click",".textfirst",function(){$(this).html('Choose Lang');$(".input-option").toggle('fast');});$(document).on("click",".input-option",function(){$(".input-option").toggle('fast');$(".textfirst").html($(this).html());$(".mm-dropdown .option").val($(this).data('value'));lang=$(this).data('value');cvids(lang);});$(document).on("click",".TbVideoNv li",function(){var vd='<iframe width="560" height="315" frameborder="0" src="'+videos[lang][$(this).data('id')]['code']+'" scrolling="no" allowfullscreen></iframe>';$(".TbVideoNv li").removeClass("active");$(this).addClass("active");$('#video_box').html(vd);return false;});var currentTime=new Date().getTime();var socialClick=localStorage.getItem('socialm');if(!socialClick||socialClick<currentTime-172800000)$(".FollowUs").show();$(".FollowUs .close").click(function(){$(".FollowUs").hide();localStorage.setItem("socialm",currentTime);});});
